-- Azeroth Completion: regions (groups of zones) and their completion rewards.
-- GENERATED by tools/zone_rewards/build.py from tools/zone_rewards/regions.py. Do not edit by hand.
--
-- Owns: regions 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, items 93800-93849, spells 64200-64249
-- (also in the client patch), azcomp_region_reward ids 1000-1499.

CREATE TABLE IF NOT EXISTS `azcomp_region` (
  `id` INT UNSIGNED NOT NULL COMMENT 'stable: character progress refers to it',
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `scope` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0 the zones in azcomp_region_zone, 1 every zone of map_id, 2 every zone',
  `map_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `icon` VARCHAR(100) NOT NULL DEFAULT '' COMMENT 'texture path shown by the addon',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COMMENT='Azeroth Completion regions';

CREATE TABLE IF NOT EXISTS `azcomp_region_zone` (
  `region_id` INT UNSIGNED NOT NULL,
  `zone_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`region_id`, `zone_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COMMENT='Azeroth Completion: zones of a region (scope 0)';

CREATE TABLE IF NOT EXISTS `azcomp_region_reward` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `region_id` INT UNSIGNED NOT NULL,
  `reward_type` VARCHAR(16) NOT NULL COMMENT 'as azcomp_milestone_reward; MONEY_PER_LEVEL uses the highest zone level',
  `value1` INT NOT NULL DEFAULT 0,
  `value2` INT NOT NULL DEFAULT 0,
  `text` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_region` (`region_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COMMENT='Azeroth Completion: reward for completing a region';

DELETE FROM `azcomp_region` WHERE `id` IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11);
DELETE FROM `azcomp_region_zone` WHERE `region_id` IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11);
DELETE FROM `azcomp_region_reward` WHERE `id` BETWEEN 1000 AND 1499;
DELETE FROM `item_template` WHERE `entry` BETWEEN 93800 AND 93849;
DELETE FROM `spell_template` WHERE `entry` BETWEEN 64200 AND 64249;
DELETE FROM `collection_mount` WHERE `itemId` BETWEEN 93800 AND 93849;

DROP TEMPORARY TABLE IF EXISTS `azc_tmp_item`;
DROP TEMPORARY TABLE IF EXISTS `azc_tmp_spell`;
CREATE TEMPORARY TABLE `azc_tmp_item` LIKE `item_template`;
CREATE TEMPORARY TABLE `azc_tmp_spell` LIKE `spell_template`;

-- The Kingdom of Azeroth: Lion's Pride Charger
INSERT INTO `azc_tmp_item` SELECT * FROM `item_template` WHERE `entry` = 83159;
UPDATE `azc_tmp_item` SET `flags` = 0, `buy_count` = 1, `buy_price` = 0, `sell_price` = 0, `allowable_class` = -1, `allowable_race` = -1, `item_level` = 1, `required_level` = 0, `required_skill` = 0, `required_skill_rank` = 0, `required_spell` = 0, `required_honor_rank` = 0, `required_city_rank` = 0, `required_reputation_faction` = 0, `required_reputation_rank` = 0, `bonding` = 1, `page_text` = 0, `start_quest` = 0, `lock_id` = 0, `random_property` = 0, `set_id` = 0, `area_bound` = 0, `map_bound` = 0, `duration` = 0, `disenchant_id` = 0, `extra_flags` = 0, `other_team_entry` = 0, `script_name` = '', `food_type` = 0, `holy_res` = 0, `fire_res` = 0, `nature_res` = 0, `frost_res` = 0, `shadow_res` = 0, `arcane_res` = 0, `stat_type1` = 0, `stat_value1` = 0, `stat_type2` = 0, `stat_value2` = 0, `stat_type3` = 0, `stat_value3` = 0, `stat_type4` = 0, `stat_value4` = 0, `stat_type5` = 0, `stat_value5` = 0, `stat_type6` = 0, `stat_value6` = 0, `stat_type7` = 0, `stat_value7` = 0, `stat_type8` = 0, `stat_value8` = 0, `stat_type9` = 0, `stat_value9` = 0, `stat_type10` = 0, `stat_value10` = 0, `entry` = 93801, `name` = 'Lion''s Pride Charger', `description` = 'Bred in the stables of Goldshire for those who rode every road of the kingdom.', `quality` = 3, `max_count` = 1, `stackable` = 1, `display_id` = (SELECT `display_id` FROM `item_template` WHERE `entry` = 18776);
INSERT INTO `item_template` SELECT * FROM `azc_tmp_item`;
DELETE FROM `azc_tmp_item`;
INSERT INTO `azc_tmp_spell` SELECT * FROM `spell_template` WHERE `entry` = 50059;
UPDATE `azc_tmp_spell` SET `nameSubtext` = '', `category` = 0, `recoveryTime` = 0, `categoryRecoveryTime` = 0, `spellFamilyName` = 0, `spellFamilyFlags` = 0, `maxLevel` = 0, `baseLevel` = 0, `spellLevel` = 0, `activeIconId` = 0, `entry` = 64201, `name` = 'Lion''s Pride Charger', `spellIconId` = 1176, `description` = 'Summons and dismisses Lion''s Pride Charger, a reward for completing The Kingdom of Azeroth. How fast it runs depends on your Riding skill.', `auraDescription` = 'Mounted.', `effectMiscValue1` = 14559;
INSERT INTO `spell_template` SELECT * FROM `azc_tmp_spell`;
DELETE FROM `azc_tmp_spell`;
INSERT INTO `collection_mount` (`itemId`, `spellId`) VALUES (93801, 64201);

-- Khaz Modan: Khaz Modan Battle Ram
INSERT INTO `azc_tmp_item` SELECT * FROM `item_template` WHERE `entry` = 83159;
UPDATE `azc_tmp_item` SET `flags` = 0, `buy_count` = 1, `buy_price` = 0, `sell_price` = 0, `allowable_class` = -1, `allowable_race` = -1, `item_level` = 1, `required_level` = 0, `required_skill` = 0, `required_skill_rank` = 0, `required_spell` = 0, `required_honor_rank` = 0, `required_city_rank` = 0, `required_reputation_faction` = 0, `required_reputation_rank` = 0, `bonding` = 1, `page_text` = 0, `start_quest` = 0, `lock_id` = 0, `random_property` = 0, `set_id` = 0, `area_bound` = 0, `map_bound` = 0, `duration` = 0, `disenchant_id` = 0, `extra_flags` = 0, `other_team_entry` = 0, `script_name` = '', `food_type` = 0, `holy_res` = 0, `fire_res` = 0, `nature_res` = 0, `frost_res` = 0, `shadow_res` = 0, `arcane_res` = 0, `stat_type1` = 0, `stat_value1` = 0, `stat_type2` = 0, `stat_value2` = 0, `stat_type3` = 0, `stat_value3` = 0, `stat_type4` = 0, `stat_value4` = 0, `stat_type5` = 0, `stat_value5` = 0, `stat_type6` = 0, `stat_value6` = 0, `stat_type7` = 0, `stat_value7` = 0, `stat_type8` = 0, `stat_value8` = 0, `stat_type9` = 0, `stat_value9` = 0, `stat_type10` = 0, `stat_value10` = 0, `entry` = 93802, `name` = 'Khaz Modan Battle Ram', `description` = 'Bred in the shadow of Ironforge. Stubborn, loyal and very loud.', `quality` = 3, `max_count` = 1, `stackable` = 1, `display_id` = (SELECT `display_id` FROM `item_template` WHERE `entry` = 19030);
INSERT INTO `item_template` SELECT * FROM `azc_tmp_item`;
DELETE FROM `azc_tmp_item`;
INSERT INTO `azc_tmp_spell` SELECT * FROM `spell_template` WHERE `entry` = 50059;
UPDATE `azc_tmp_spell` SET `nameSubtext` = '', `category` = 0, `recoveryTime` = 0, `categoryRecoveryTime` = 0, `spellFamilyName` = 0, `spellFamilyFlags` = 0, `maxLevel` = 0, `baseLevel` = 0, `spellLevel` = 0, `activeIconId` = 0, `entry` = 64202, `name` = 'Khaz Modan Battle Ram', `spellIconId` = 1177, `description` = 'Summons and dismisses Khaz Modan Battle Ram, a reward for completing Khaz Modan. How fast it runs depends on your Riding skill.', `auraDescription` = 'Mounted.', `effectMiscValue1` = 14745;
INSERT INTO `spell_template` SELECT * FROM `azc_tmp_spell`;
DELETE FROM `azc_tmp_spell`;
INSERT INTO `collection_mount` (`itemId`, `spellId`) VALUES (93802, 64202);

-- Lordaeron: Lordaeron Deathcharger
INSERT INTO `azc_tmp_item` SELECT * FROM `item_template` WHERE `entry` = 83159;
UPDATE `azc_tmp_item` SET `flags` = 0, `buy_count` = 1, `buy_price` = 0, `sell_price` = 0, `allowable_class` = -1, `allowable_race` = -1, `item_level` = 1, `required_level` = 0, `required_skill` = 0, `required_skill_rank` = 0, `required_spell` = 0, `required_honor_rank` = 0, `required_city_rank` = 0, `required_reputation_faction` = 0, `required_reputation_rank` = 0, `bonding` = 1, `page_text` = 0, `start_quest` = 0, `lock_id` = 0, `random_property` = 0, `set_id` = 0, `area_bound` = 0, `map_bound` = 0, `duration` = 0, `disenchant_id` = 0, `extra_flags` = 0, `other_team_entry` = 0, `script_name` = '', `food_type` = 0, `holy_res` = 0, `fire_res` = 0, `nature_res` = 0, `frost_res` = 0, `shadow_res` = 0, `arcane_res` = 0, `stat_type1` = 0, `stat_value1` = 0, `stat_type2` = 0, `stat_value2` = 0, `stat_type3` = 0, `stat_value3` = 0, `stat_type4` = 0, `stat_value4` = 0, `stat_type5` = 0, `stat_value5` = 0, `stat_type6` = 0, `stat_value6` = 0, `stat_type7` = 0, `stat_value7` = 0, `stat_type8` = 0, `stat_value8` = 0, `stat_type9` = 0, `stat_value9` = 0, `stat_type10` = 0, `stat_value10` = 0, `entry` = 93803, `name` = 'Lordaeron Deathcharger', `description` = 'It remembers when Lordaeron still stood.', `quality` = 3, `max_count` = 1, `stackable` = 1, `display_id` = (SELECT `display_id` FROM `item_template` WHERE `entry` = 81245);
INSERT INTO `item_template` SELECT * FROM `azc_tmp_item`;
DELETE FROM `azc_tmp_item`;
INSERT INTO `azc_tmp_spell` SELECT * FROM `spell_template` WHERE `entry` = 50059;
UPDATE `azc_tmp_spell` SET `nameSubtext` = '', `category` = 0, `recoveryTime` = 0, `categoryRecoveryTime` = 0, `spellFamilyName` = 0, `spellFamilyFlags` = 0, `maxLevel` = 0, `baseLevel` = 0, `spellLevel` = 0, `activeIconId` = 0, `entry` = 64203, `name` = 'Lordaeron Deathcharger', `spellIconId` = 1241, `description` = 'Summons and dismisses Lordaeron Deathcharger, a reward for completing Lordaeron. How fast it runs depends on your Riding skill.', `auraDescription` = 'Mounted.', `effectMiscValue1` = 80313;
INSERT INTO `spell_template` SELECT * FROM `azc_tmp_spell`;
DELETE FROM `azc_tmp_spell`;
INSERT INTO `collection_mount` (`itemId`, `spellId`) VALUES (93803, 64203);

-- Quel'Thalas: Sunstrider Unicorn
INSERT INTO `azc_tmp_item` SELECT * FROM `item_template` WHERE `entry` = 83159;
UPDATE `azc_tmp_item` SET `flags` = 0, `buy_count` = 1, `buy_price` = 0, `sell_price` = 0, `allowable_class` = -1, `allowable_race` = -1, `item_level` = 1, `required_level` = 0, `required_skill` = 0, `required_skill_rank` = 0, `required_spell` = 0, `required_honor_rank` = 0, `required_city_rank` = 0, `required_reputation_faction` = 0, `required_reputation_rank` = 0, `bonding` = 1, `page_text` = 0, `start_quest` = 0, `lock_id` = 0, `random_property` = 0, `set_id` = 0, `area_bound` = 0, `map_bound` = 0, `duration` = 0, `disenchant_id` = 0, `extra_flags` = 0, `other_team_entry` = 0, `script_name` = '', `food_type` = 0, `holy_res` = 0, `fire_res` = 0, `nature_res` = 0, `frost_res` = 0, `shadow_res` = 0, `arcane_res` = 0, `stat_type1` = 0, `stat_value1` = 0, `stat_type2` = 0, `stat_value2` = 0, `stat_type3` = 0, `stat_value3` = 0, `stat_type4` = 0, `stat_value4` = 0, `stat_type5` = 0, `stat_value5` = 0, `stat_type6` = 0, `stat_value6` = 0, `stat_type7` = 0, `stat_value7` = 0, `stat_type8` = 0, `stat_value8` = 0, `stat_type9` = 0, `stat_value9` = 0, `stat_type10` = 0, `stat_value10` = 0, `entry` = 93804, `name` = 'Sunstrider Unicorn', `description` = 'A gift of the quel''dorei to friends of Alah''Thalas.', `quality` = 3, `max_count` = 1, `stackable` = 1, `display_id` = (SELECT `display_id` FROM `item_template` WHERE `entry` = 80459);
INSERT INTO `item_template` SELECT * FROM `azc_tmp_item`;
DELETE FROM `azc_tmp_item`;
INSERT INTO `azc_tmp_spell` SELECT * FROM `spell_template` WHERE `entry` = 50059;
UPDATE `azc_tmp_spell` SET `nameSubtext` = '', `category` = 0, `recoveryTime` = 0, `categoryRecoveryTime` = 0, `spellFamilyName` = 0, `spellFamilyFlags` = 0, `maxLevel` = 0, `baseLevel` = 0, `spellLevel` = 0, `activeIconId` = 0, `entry` = 64204, `name` = 'Sunstrider Unicorn', `spellIconId` = 1176, `description` = 'Summons and dismisses Sunstrider Unicorn, a reward for completing Quel''Thalas. How fast it runs depends on your Riding skill.', `auraDescription` = 'Mounted.', `effectMiscValue1` = 40045;
INSERT INTO `spell_template` SELECT * FROM `azc_tmp_spell`;
DELETE FROM `azc_tmp_spell`;
INSERT INTO `collection_mount` (`itemId`, `spellId`) VALUES (93804, 64204);

-- The Isles: Islander's Sea Turtle
INSERT INTO `azc_tmp_item` SELECT * FROM `item_template` WHERE `entry` = 83159;
UPDATE `azc_tmp_item` SET `flags` = 0, `buy_count` = 1, `buy_price` = 0, `sell_price` = 0, `allowable_class` = -1, `allowable_race` = -1, `item_level` = 1, `required_level` = 0, `required_skill` = 0, `required_skill_rank` = 0, `required_spell` = 0, `required_honor_rank` = 0, `required_city_rank` = 0, `required_reputation_faction` = 0, `required_reputation_rank` = 0, `bonding` = 1, `page_text` = 0, `start_quest` = 0, `lock_id` = 0, `random_property` = 0, `set_id` = 0, `area_bound` = 0, `map_bound` = 0, `duration` = 0, `disenchant_id` = 0, `extra_flags` = 0, `other_team_entry` = 0, `script_name` = '', `food_type` = 0, `holy_res` = 0, `fire_res` = 0, `nature_res` = 0, `frost_res` = 0, `shadow_res` = 0, `arcane_res` = 0, `stat_type1` = 0, `stat_value1` = 0, `stat_type2` = 0, `stat_value2` = 0, `stat_type3` = 0, `stat_value3` = 0, `stat_type4` = 0, `stat_value4` = 0, `stat_type5` = 0, `stat_value5` = 0, `stat_type6` = 0, `stat_value6` = 0, `stat_type7` = 0, `stat_value7` = 0, `stat_type8` = 0, `stat_value8` = 0, `stat_type9` = 0, `stat_value9` = 0, `stat_type10` = 0, `stat_value10` = 0, `entry` = 93805, `name` = 'Islander''s Sea Turtle', `description` = 'Slow and steady. Somehow always gets there first.', `quality` = 3, `max_count` = 1, `stackable` = 1, `display_id` = (SELECT `display_id` FROM `item_template` WHERE `entry` = 23720);
INSERT INTO `item_template` SELECT * FROM `azc_tmp_item`;
DELETE FROM `azc_tmp_item`;
INSERT INTO `azc_tmp_spell` SELECT * FROM `spell_template` WHERE `entry` = 50059;
UPDATE `azc_tmp_spell` SET `nameSubtext` = '', `category` = 0, `recoveryTime` = 0, `categoryRecoveryTime` = 0, `spellFamilyName` = 0, `spellFamilyFlags` = 0, `maxLevel` = 0, `baseLevel` = 0, `spellLevel` = 0, `activeIconId` = 0, `entry` = 64205, `name` = 'Islander''s Sea Turtle', `spellIconId` = 2050, `description` = 'Summons and dismisses Islander''s Sea Turtle, a reward for completing The Isles. How fast it runs depends on your Riding skill.', `auraDescription` = 'Mounted.', `effectMiscValue1` = 17266;
INSERT INTO `spell_template` SELECT * FROM `azc_tmp_spell`;
DELETE FROM `azc_tmp_spell`;
INSERT INTO `collection_mount` (`itemId`, `spellId`) VALUES (93805, 64205);

-- Northern Kalimdor: Grovewarden Stag
INSERT INTO `azc_tmp_item` SELECT * FROM `item_template` WHERE `entry` = 83159;
UPDATE `azc_tmp_item` SET `flags` = 0, `buy_count` = 1, `buy_price` = 0, `sell_price` = 0, `allowable_class` = -1, `allowable_race` = -1, `item_level` = 1, `required_level` = 0, `required_skill` = 0, `required_skill_rank` = 0, `required_spell` = 0, `required_honor_rank` = 0, `required_city_rank` = 0, `required_reputation_faction` = 0, `required_reputation_rank` = 0, `bonding` = 1, `page_text` = 0, `start_quest` = 0, `lock_id` = 0, `random_property` = 0, `set_id` = 0, `area_bound` = 0, `map_bound` = 0, `duration` = 0, `disenchant_id` = 0, `extra_flags` = 0, `other_team_entry` = 0, `script_name` = '', `food_type` = 0, `holy_res` = 0, `fire_res` = 0, `nature_res` = 0, `frost_res` = 0, `shadow_res` = 0, `arcane_res` = 0, `stat_type1` = 0, `stat_value1` = 0, `stat_type2` = 0, `stat_value2` = 0, `stat_type3` = 0, `stat_value3` = 0, `stat_type4` = 0, `stat_value4` = 0, `stat_type5` = 0, `stat_value5` = 0, `stat_type6` = 0, `stat_value6` = 0, `stat_type7` = 0, `stat_value7` = 0, `stat_type8` = 0, `stat_value8` = 0, `stat_type9` = 0, `stat_value9` = 0, `stat_type10` = 0, `stat_value10` = 0, `entry` = 93806, `name` = 'Grovewarden Stag', `description` = 'Walks in the footsteps of Cenarius.', `quality` = 3, `max_count` = 1, `stackable` = 1, `display_id` = (SELECT `display_id` FROM `item_template` WHERE `entry` = 50406);
INSERT INTO `item_template` SELECT * FROM `azc_tmp_item`;
DELETE FROM `azc_tmp_item`;
INSERT INTO `azc_tmp_spell` SELECT * FROM `spell_template` WHERE `entry` = 50059;
UPDATE `azc_tmp_spell` SET `nameSubtext` = '', `category` = 0, `recoveryTime` = 0, `categoryRecoveryTime` = 0, `spellFamilyName` = 0, `spellFamilyFlags` = 0, `maxLevel` = 0, `baseLevel` = 0, `spellLevel` = 0, `activeIconId` = 0, `entry` = 64206, `name` = 'Grovewarden Stag', `spellIconId` = 2122, `description` = 'Summons and dismisses Grovewarden Stag, a reward for completing Northern Kalimdor. How fast it runs depends on your Riding skill.', `auraDescription` = 'Mounted.', `effectMiscValue1` = 50097;
INSERT INTO `spell_template` SELECT * FROM `azc_tmp_spell`;
DELETE FROM `azc_tmp_spell`;
INSERT INTO `collection_mount` (`itemId`, `spellId`) VALUES (93806, 64206);

-- The Heart of Kalimdor: Crossroads War Kodo
INSERT INTO `azc_tmp_item` SELECT * FROM `item_template` WHERE `entry` = 83159;
UPDATE `azc_tmp_item` SET `flags` = 0, `buy_count` = 1, `buy_price` = 0, `sell_price` = 0, `allowable_class` = -1, `allowable_race` = -1, `item_level` = 1, `required_level` = 0, `required_skill` = 0, `required_skill_rank` = 0, `required_spell` = 0, `required_honor_rank` = 0, `required_city_rank` = 0, `required_reputation_faction` = 0, `required_reputation_rank` = 0, `bonding` = 1, `page_text` = 0, `start_quest` = 0, `lock_id` = 0, `random_property` = 0, `set_id` = 0, `area_bound` = 0, `map_bound` = 0, `duration` = 0, `disenchant_id` = 0, `extra_flags` = 0, `other_team_entry` = 0, `script_name` = '', `food_type` = 0, `holy_res` = 0, `fire_res` = 0, `nature_res` = 0, `frost_res` = 0, `shadow_res` = 0, `arcane_res` = 0, `stat_type1` = 0, `stat_value1` = 0, `stat_type2` = 0, `stat_value2` = 0, `stat_type3` = 0, `stat_value3` = 0, `stat_type4` = 0, `stat_value4` = 0, `stat_type5` = 0, `stat_value5` = 0, `stat_type6` = 0, `stat_value6` = 0, `stat_type7` = 0, `stat_value7` = 0, `stat_type8` = 0, `stat_value8` = 0, `stat_type9` = 0, `stat_value9` = 0, `stat_type10` = 0, `stat_value10` = 0, `entry` = 93807, `name` = 'Crossroads War Kodo', `description` = 'Has carried caravans across every mile of the Barrens.', `quality` = 3, `max_count` = 1, `stackable` = 1, `display_id` = (SELECT `display_id` FROM `item_template` WHERE `entry` = 81237);
INSERT INTO `item_template` SELECT * FROM `azc_tmp_item`;
DELETE FROM `azc_tmp_item`;
INSERT INTO `azc_tmp_spell` SELECT * FROM `spell_template` WHERE `entry` = 50059;
UPDATE `azc_tmp_spell` SET `nameSubtext` = '', `category` = 0, `recoveryTime` = 0, `categoryRecoveryTime` = 0, `spellFamilyName` = 0, `spellFamilyFlags` = 0, `maxLevel` = 0, `baseLevel` = 0, `spellLevel` = 0, `activeIconId` = 0, `entry` = 64207, `name` = 'Crossroads War Kodo', `spellIconId` = 1684, `description` = 'Summons and dismisses Crossroads War Kodo, a reward for completing The Heart of Kalimdor. How fast it runs depends on your Riding skill.', `auraDescription` = 'Mounted.', `effectMiscValue1` = 81102;
INSERT INTO `spell_template` SELECT * FROM `azc_tmp_spell`;
DELETE FROM `azc_tmp_spell`;
INSERT INTO `collection_mount` (`itemId`, `spellId`) VALUES (93807, 64207);

-- Southern Kalimdor: Un'Goro Ravasaur
INSERT INTO `azc_tmp_item` SELECT * FROM `item_template` WHERE `entry` = 83159;
UPDATE `azc_tmp_item` SET `flags` = 0, `buy_count` = 1, `buy_price` = 0, `sell_price` = 0, `allowable_class` = -1, `allowable_race` = -1, `item_level` = 1, `required_level` = 0, `required_skill` = 0, `required_skill_rank` = 0, `required_spell` = 0, `required_honor_rank` = 0, `required_city_rank` = 0, `required_reputation_faction` = 0, `required_reputation_rank` = 0, `bonding` = 1, `page_text` = 0, `start_quest` = 0, `lock_id` = 0, `random_property` = 0, `set_id` = 0, `area_bound` = 0, `map_bound` = 0, `duration` = 0, `disenchant_id` = 0, `extra_flags` = 0, `other_team_entry` = 0, `script_name` = '', `food_type` = 0, `holy_res` = 0, `fire_res` = 0, `nature_res` = 0, `frost_res` = 0, `shadow_res` = 0, `arcane_res` = 0, `stat_type1` = 0, `stat_value1` = 0, `stat_type2` = 0, `stat_value2` = 0, `stat_type3` = 0, `stat_value3` = 0, `stat_type4` = 0, `stat_value4` = 0, `stat_type5` = 0, `stat_value5` = 0, `stat_type6` = 0, `stat_value6` = 0, `stat_type7` = 0, `stat_value7` = 0, `stat_type8` = 0, `stat_value8` = 0, `stat_type9` = 0, `stat_value9` = 0, `stat_type10` = 0, `stat_value10` = 0, `entry` = 93808, `name` = 'Un''Goro Ravasaur', `description` = 'Hatched in the crater. Fears nothing, eats anything.', `quality` = 3, `max_count` = 1, `stackable` = 1, `display_id` = (SELECT `display_id` FROM `item_template` WHERE `entry` = 8586);
INSERT INTO `item_template` SELECT * FROM `azc_tmp_item`;
DELETE FROM `azc_tmp_item`;
INSERT INTO `azc_tmp_spell` SELECT * FROM `spell_template` WHERE `entry` = 50059;
UPDATE `azc_tmp_spell` SET `nameSubtext` = '', `category` = 0, `recoveryTime` = 0, `categoryRecoveryTime` = 0, `spellFamilyName` = 0, `spellFamilyFlags` = 0, `maxLevel` = 0, `baseLevel` = 0, `spellLevel` = 0, `activeIconId` = 0, `entry` = 64208, `name` = 'Un''Goro Ravasaur', `spellIconId` = 1584, `description` = 'Summons and dismisses Un''Goro Ravasaur, a reward for completing Southern Kalimdor. How fast it runs depends on your Riding skill.', `auraDescription` = 'Mounted.', `effectMiscValue1` = 6507;
INSERT INTO `spell_template` SELECT * FROM `azc_tmp_spell`;
DELETE FROM `azc_tmp_spell`;
INSERT INTO `collection_mount` (`itemId`, `spellId`) VALUES (93808, 64208);

-- Azeroth: Azerothian Champion's Charger
INSERT INTO `azc_tmp_item` SELECT * FROM `item_template` WHERE `entry` = 83159;
UPDATE `azc_tmp_item` SET `flags` = 0, `buy_count` = 1, `buy_price` = 0, `sell_price` = 0, `allowable_class` = -1, `allowable_race` = -1, `item_level` = 1, `required_level` = 0, `required_skill` = 0, `required_skill_rank` = 0, `required_spell` = 0, `required_honor_rank` = 0, `required_city_rank` = 0, `required_reputation_faction` = 0, `required_reputation_rank` = 0, `bonding` = 1, `page_text` = 0, `start_quest` = 0, `lock_id` = 0, `random_property` = 0, `set_id` = 0, `area_bound` = 0, `map_bound` = 0, `duration` = 0, `disenchant_id` = 0, `extra_flags` = 0, `other_team_entry` = 0, `script_name` = '', `food_type` = 0, `holy_res` = 0, `fire_res` = 0, `nature_res` = 0, `frost_res` = 0, `shadow_res` = 0, `arcane_res` = 0, `stat_type1` = 0, `stat_value1` = 0, `stat_type2` = 0, `stat_value2` = 0, `stat_type3` = 0, `stat_value3` = 0, `stat_type4` = 0, `stat_value4` = 0, `stat_type5` = 0, `stat_value5` = 0, `stat_type6` = 0, `stat_value6` = 0, `stat_type7` = 0, `stat_value7` = 0, `stat_type8` = 0, `stat_value8` = 0, `stat_type9` = 0, `stat_value9` = 0, `stat_type10` = 0, `stat_value10` = 0, `entry` = 93811, `name` = 'Azerothian Champion''s Charger', `description` = 'Ridden only by those who have seen all of Azeroth.', `quality` = 4, `max_count` = 1, `stackable` = 1, `display_id` = (SELECT `display_id` FROM `item_template` WHERE `entry` = 80692);
INSERT INTO `item_template` SELECT * FROM `azc_tmp_item`;
DELETE FROM `azc_tmp_item`;
INSERT INTO `azc_tmp_spell` SELECT * FROM `spell_template` WHERE `entry` = 50059;
UPDATE `azc_tmp_spell` SET `nameSubtext` = '', `category` = 0, `recoveryTime` = 0, `categoryRecoveryTime` = 0, `spellFamilyName` = 0, `spellFamilyFlags` = 0, `maxLevel` = 0, `baseLevel` = 0, `spellLevel` = 0, `activeIconId` = 0, `entry` = 64211, `name` = 'Azerothian Champion''s Charger', `spellIconId` = 1179, `description` = 'Summons and dismisses Azerothian Champion''s Charger, a reward for completing Azeroth. How fast it runs depends on your Riding skill.', `auraDescription` = 'Mounted.', `effectMiscValue1` = 80160;
INSERT INTO `spell_template` SELECT * FROM `azc_tmp_spell`;
DELETE FROM `azc_tmp_spell`;
INSERT INTO `collection_mount` (`itemId`, `spellId`) VALUES (93811, 64211);

INSERT INTO `azcomp_region` (`id`, `name`, `description`, `scope`, `map_id`, `sort_order`, `icon`) VALUES
(1, 'The Kingdom of Azeroth', 'Elwynn''s fields to the scorched Blasted Lands.', 0, 0, 0, 'Interface\\Icons\\INV_BannerPVP_02'),
(2, 'Khaz Modan', 'The dwarven mountains, from Dun Morogh to the Burning Steppes.', 0, 0, 1, 'Interface\\Icons\\INV_Hammer_Unique_Sulfuras'),
(3, 'Lordaeron', 'The fallen northern kingdom, from Tirisfal to the plague-blighted east.', 0, 0, 2, 'Interface\\Icons\\Spell_Shadow_RaiseDead'),
(4, 'Quel''Thalas', 'The forests of the high elves.', 0, 0, 3, 'Interface\\Icons\\Spell_Holy_MindVision'),
(5, 'The Isles', 'The islands of the South Seas and beyond.', 0, 0, 4, 'Interface\\Icons\\INV_Misc_Shell_01'),
(6, 'Northern Kalimdor', 'The ancient forests of the night elves, from Teldrassil to Mount Hyjal.', 0, 0, 5, 'Interface\\Icons\\Ability_Druid_Dreamstate'),
(7, 'The Heart of Kalimdor', 'Durotar and Mulgore, the Barrens and the lands around them.', 0, 0, 6, 'Interface\\Icons\\INV_Misc_Head_Tauren_01'),
(8, 'Southern Kalimdor', 'Feralas, Tanaris, Un''Goro and the sands of Silithus.', 0, 0, 7, 'Interface\\Icons\\INV_Misc_Desecrated_PlateHelm'),
(9, 'Eastern Kingdoms', 'Every zone of the Eastern Kingdoms.', 1, 0, 8, 'Interface\\Icons\\INV_Misc_Map_01'),
(10, 'Kalimdor', 'Every zone of Kalimdor.', 1, 1, 9, 'Interface\\Icons\\INV_Misc_Map02'),
(11, 'Azeroth', 'Every zone of the world.', 2, 0, 10, 'Interface\\Icons\\INV_Misc_Orb_05');
INSERT INTO `azcomp_region_zone` (`region_id`, `zone_id`) VALUES
(1, 12),
(1, 40),
(1, 44),
(1, 10),
(1, 33),
(1, 41),
(1, 8),
(1, 4),
(2, 1),
(2, 38),
(2, 11),
(2, 51),
(2, 3),
(2, 46),
(3, 85),
(3, 130),
(3, 267),
(3, 36),
(3, 45),
(3, 47),
(3, 28),
(3, 139),
(3, 5179),
(3, 4012),
(4, 5225),
(4, 2040),
(5, 408),
(5, 409),
(5, 5121),
(5, 5536),
(5, 5024),
(6, 141),
(6, 148),
(6, 331),
(6, 361),
(6, 618),
(6, 493),
(6, 16),
(6, 616),
(7, 14),
(7, 215),
(7, 17),
(7, 406),
(7, 405),
(7, 400),
(7, 15),
(8, 357),
(8, 440),
(8, 490),
(8, 1377);
INSERT INTO `azcomp_region_reward` (`id`, `region_id`, `reward_type`, `value1`, `value2`, `text`) VALUES
(1010, 1, 'MONEY', 250000, 0, 'region'),
(1011, 1, 'ITEM', 93801, 1, 'region mount'),
(1020, 2, 'MONEY', 250000, 0, 'region'),
(1021, 2, 'ITEM', 93802, 1, 'region mount'),
(1030, 3, 'MONEY', 250000, 0, 'region'),
(1031, 3, 'ITEM', 93803, 1, 'region mount'),
(1040, 4, 'MONEY', 250000, 0, 'region'),
(1041, 4, 'ITEM', 93804, 1, 'region mount'),
(1050, 5, 'MONEY', 250000, 0, 'region'),
(1051, 5, 'ITEM', 93805, 1, 'region mount'),
(1060, 6, 'MONEY', 250000, 0, 'region'),
(1061, 6, 'ITEM', 93806, 1, 'region mount'),
(1070, 7, 'MONEY', 250000, 0, 'region'),
(1071, 7, 'ITEM', 93807, 1, 'region mount'),
(1080, 8, 'MONEY', 250000, 0, 'region'),
(1081, 8, 'ITEM', 93808, 1, 'region mount'),
(1090, 9, 'MONEY', 500000, 0, 'region'),
(1091, 9, 'TITLE', 120, 0, 'Pathfinder of the Eastern Kingdoms'),
(1100, 10, 'MONEY', 500000, 0, 'region'),
(1101, 10, 'TITLE', 121, 0, 'Pathfinder of Kalimdor'),
(1110, 11, 'MONEY', 1000000, 0, 'region'),
(1111, 11, 'ITEM', 93811, 1, 'region mount'),
(1112, 11, 'TITLE', 122, 0, 'Master of Azeroth');

DROP TEMPORARY TABLE `azc_tmp_item`;
DROP TEMPORARY TABLE `azc_tmp_spell`;
