# Themed completion rewards, one set per zone. build.py turns this into the world SQL, the
# client spell rows and the addon's title names.
#
# Every "look" is an existing item entry whose appearance (display id) the reward borrows.
# Tabards, shirts and cloaks are copies of that item; the other rewards only take its icon.
# "tele" is a game_tele name (checked to lie inside the zone). "model" and "form" are existing
# creature entries: the pet borrows the model's appearance, the fun consumable transforms the
# player into the form.
#
# The order is fixed: a zone's position decides its item, spell, creature and title ids, so
# append new zones at the end and never reorder or remove (retire a zone with retired=True).
# Retired zones stop awarding rewards; their definitions stay available for existing owners.
#
# Buff presets are in build.py (BUFFS). Avoid ';' in texts (the DB updater splits on it).


def Z(area, name, title, tabard, wear, buff, charm, pet, fun, retired=False):
    return dict(area=area, name=name, title=title, tabard=tabard, wear=wear, buff=buff,
                charm=charm, pet=pet, fun=fun, retired=retired)


# tabard = (name, look)                       wear = (name, look)  shirt or cloak
# buff   = (item name, look, aura name, preset)
# charm  = (item name, look, tele, place)
# pet    = (name, model, scale, look, flavour)
# fun    = (item name, look, form, "you become ...")
ZONES = [
    # --- Eastern Kingdoms ---------------------------------------------------------------------
    Z(12, "Elwynn Forest", "Defender of Elwynn",
      ("Tabard of the Elwynn Watch", 11364), ("Lion's Pride Inn Shirt", 2576),
      ("Goldshire Honey Bread", 4601, "Elwynn Harvest", "stats"),
      ("Elwynn Wayfarer's Token", 51603, "ElwynnForest", "the heart of Elwynn Forest"),
      ("Lil' Hogger", 448, 0.35, 10394, "Still convinced the whole forest belongs to him."),
      ("Kobold Candle Hat", 1630, 40, "a kobold miner")),
    Z(40, "Westfall", "Sentinel of Westfall",
      ("Tabard of the People's Militia", 50090), ("Saldean Harvest Cloak", 60369),
      ("Furlbrow's Hearty Stew", 733, "Hearty Stew", "health"),
      ("Saldean's Farm Lantern", 2714, "Westfall", "Saldean's Farm"),
      ("Harvest Watcher Jr.", 114, 0.3, 11110, "Guards a patch of dirt that only it can see."),
      ("Jar of Dust Devil", 8151, 832, "a dust devil")),
    Z(44, "Redridge Mountains", "Warden of Redridge",
      ("Tabard of Lakeshire", 15197), ("Redridge Angler's Shirt", 4344),
      ("Lakeshire Fish Fry", 13934, "Redridge Resolve", "attack_power"),
      ("Lakeshire Bridge Bell", 17849, "RedridgeMountains", "the Redridge hills"),
      ("Blackrock Worg Pup", 7055, 0.35, 50085, "Taken from the Blackrock kennels. It forgave you."),
      ("Riverpaw Snout Mask", 777, 117, "a Riverpaw gnoll")),
    Z(10, "Duskwood", "Night Watchman",
      ("Tabard of the Night Watch", 50091), ("Raven Hill Mourning Shroud", 6751),
      ("Darkshire Night Brew", 10841, "Watchman's Vigil", "armor"),
      ("Raven Hill Lantern", 1630, "Duskwood", "the Duskwood crossroads"),
      ("Stitches Jr.", 412, 0.3, 50013, "Shuffles after you, moaning about the Night Watch."),
      ("Abercrombie's Peculiar Tonic", 8529, 846, "a shambling ghoul")),
    Z(33, "Stranglethorn Vale", "Hemet's Rival",
      ("Tabard of the Blackwater Cartel", 50038), ("Faded Green Hills Shirt", 17723),
      ("Hemet's Jungle Jerky", 3727, "Hunter's Instinct", "crit"),
      ("Booty Bay Doubloon", 51603, "BootyBay", "Booty Bay"),
      ("Mukla Jr.", 1559, 0.3, 13582, "Beats his chest at anything bigger than him. Which is everything."),
      ("Bloodsail Grog", 17048, 1563, "a Bloodsail swashbuckler")),
    Z(1, "Dun Morogh", "Snowbound Mountaineer",
      ("Tabard of the Ironforge Mountaineers", 80303), ("Thunderbrew Brewer's Shirt", 11840),
      ("Thunderbrew Lager", 2686, "Dwarven Fortitude", "armor"),
      ("Brewnall Village Keg Tap", 3745, "BrewnallVillage", "Brewnall Village"),
      ("Little Ram Kid", 2098, 0.35, 50014, "Headbutts snowmen. Wins, usually."),
      ("Frostmane Tribal Mask", 51245, 1120, "a Frostmane troll")),
    Z(38, "Loch Modan", "Keeper of the Loch",
      ("Tabard of Thelsamar", 15199), ("Stonewrought Dam Cloak", 4504),
      ("Thelsamar Smoked Sausage", 6890, "Mountain Hardiness", "dodge"),
      ("Stonewrought Dam Key", 2629, "StonewroughtDam", "the Stonewrought Dam"),
      ("Mountain Boar Piglet", 1191, 0.3, 50058, "Smells faintly of Thelsamar blood sausage. Do not tell it."),
      ("Stonesplinter Rock Candy", 80166, 1161, "a Stonesplinter trogg")),
    Z(11, "Wetlands", "Warden of the Green Belt",
      ("Tabard of Menethil Harbor", 50087), ("Mosshide Fen Cloak", 4735),
      ("Menethil Clam Chowder", 12215, "Harbor Legs", "swim"),
      ("Green Belt Waystone", 3408, "Wetlands", "the Green Belt"),
      ("Mottled Raptor Hatchling", 1020, 0.35, 81183, "Hatched in the Wetlands mud and never quite dried off."),
      ("Dragonmaw Warpaint", 51245, 2102, "a Dragonmaw orc")),
    Z(130, "Silverpine Forest", "Sentinel of Silverpine",
      ("Tabard of Pyrewood", 61369), ("Silverpine Woodsman's Cloak", 4710),
      ("Pyrewood Moonshine", 2723, "Moonlit Vigor", "regen"),
      ("Silverpine Pinecone", 61199, "SilverpineForest", "the Silverpine woods"),
      ("Moonrage Pup", 1769, 0.3, 8497, "Howls at the moon, then hides behind your legs."),
      ("Shadowfang Pelt", 777, 3851, "a Shadowfang worgen")),
    Z(267, "Hillsbrad Foothills", "Peacekeeper of Hillsbrad",
      ("Hillsbrad Militia Tabard", 50376), ("Hillsbrad Farmhand's Shirt", 148),
      ("Hillsbrad Fresh Milk", 1179, "Farmhand's Health", "healing"),
      ("Hillsbrad Fence Post", 17849, "HillsbradFoothills", "the Hillsbrad farms"),
      ("Hillsbrad Bear Cub", 80151, 0.4, 51889, "Raided the Southshore pantry twice before breakfast."),
      ("Syndicate Footpad Mask", 51245, 2240, "a Syndicate footpad")),
    Z(36, "Alterac Mountains", "Yeti Wrangler",
      ("Tabard of Alterac", 50089), ("Ravenholdt Shadow Cloak", 4447),
      ("Alterac Swiss Fondue", 12215, "Mountain Warmth", "resist_frost"),
      ("Gallows' Corner Signet", 81025, "AlteracMountains", "Gallows' Corner"),
      ("Alterac Yeti Cub", 2248, 0.3, 21309, "Fluffy, furious and about knee high."),
      ("Dalaran Apprentice Robes", 51245, 1867, "a Dalaran apprentice")),
    Z(45, "Arathi Highlands", "Champion of Arathor",
      ("Arathor Highland Tabard", 20132), ("Stromgarde Knight's Cloak", 7460),
      ("Hammerfall Highland Mead", 4595, "Highland Resolve", "damage_taken"),
      ("Arathor Standing Stone", 3408, "ArathiHighlands", "the Arathi Highlands"),
      ("Highland Strider Chick", 2559, 0.3, 81243, "Runs everywhere. Arrives nowhere."),
      ("Boulderfist Club Juice", 8152, 2562, "a Boulderfist ogre")),
    Z(47, "The Hinterlands", "Friend of the Wildhammer",
      ("Aerie Peak Tabard", 80312), ("Gryphon Rider's Cloak", 15624),
      ("Wildhammer Firewater", 20709, "Stormrider's Fervor", "speed"),
      ("Hinterlands Gryphon Feather", 11417, "TheHinterlands", "the Hinterlands"),
      ("Gryphon Hatchling", 2347, 0.25, 50080, "The Wildhammer swear it will grow into its beak."),
      ("Vilebranch Witch Doctor Mask", 51245, 2640, "a Vilebranch witch doctor")),
    Z(28, "Western Plaguelands", "Hope of Andorhal",
      ("Tabard of the Silver Hand", 80311), ("Caer Darrow Archivist Cape", 13386),
      ("Andorhal Holy Water", 8766, "Purified Spirit", "resist_nature"),
      ("Tattered Banner of Andorhal", 60201, "WesternPlaguelands", "the Western Plaguelands"),
      ("Little Rattlecage", 1890, 0.35, 80166, "Rattles happily. Loses a rib now and then."),
      ("Scholomance Tutor's Tonic", 8529, 10498, "a spectral tutor")),
    Z(139, "Eastern Plaguelands", "Light's Hope Vanguard",
      ("Tabard of Light's Hope", 22999), ("Crusader's Linen Shirt", 41270),
      ("Argent Dawn Rations", 4601, "Argent Discipline", "hit"),
      ("Light's Hope Chapel Seal", 1490, "Light'sHopeChapel", "Light's Hope Chapel"),
      ("Plaguehound Runt", 8596, 0.35, 20769, "Cured, mostly. Keep it away from the grain."),
      ("Crypt Fiend Carapace Dust", 80166, 8555, "a crypt fiend")),
    Z(85, "Tirisfal Glades", "Warden of the Glades",
      ("Tabard of the Deathguard", 80309), ("Brill Gravedigger's Shirt", 3427),
      ("Tirisfal Pumpkin Pie", 4602, "Harvest of the Forsaken", "attack_power"),
      ("Tirisfal Lantern", 1630, "TirisfalGlades", "Tirisfal Glades"),
      ("Duskbat Pup", 1512, 0.25, 51858, "Sleeps upside down on your backpack."),
      ("Scarlet Convert's Robe", 8529, 1506, "a Scarlet convert")),
    Z(3, "Badlands", "Dustbowl Prospector",
      ("Tabard of the Badlands Expedition", 81205), ("Dustbowl Duster", 6604),
      ("Kargath Scorpid Surprise", 2680, "Desert Hardiness", "resist_fire"),
      ("Badlands Prospector's Rune", 3745, "Badlands", "the Badlands"),
      ("Crystal Spine Hatchling", 689, 0.3, 12529, "Its stare turns nothing to stone, though it keeps trying."),
      ("Stonevault Trogg Musk", 8151, 2893, "a Stonevault trogg")),
    Z(51, "Searing Gorge", "Thorium Pathfinder",
      ("Tabard of the Thorium Brotherhood", 23705), ("Cauldron Ash Cloak", 3475),
      ("Thorium Point Fire Ale", 2686, "Forgeheart", "resist_fire"),
      ("Thorium Point Signet", 81025, "ThoriumPoint", "Thorium Point"),
      ("Searing Lava Crab", 9700, 0.3, 92020, "Pleasantly warm. Do not pick it up."),
      ("Dark Iron Disguise Kit", 51245, 1051, "a Dark Iron dwarf")),
    Z(46, "Burning Steppes", "Scourge of Blackrock",
      ("Tabard of Morgan's Vigil", 81081), ("Blackrock Ember Cape", 13109),
      ("Flame Crest Firewater", 8151, "Emberheart", "damage"),
      ("Morgan's Vigil Beacon", 2714, "BurningSteppes", "the Burning Steppes"),
      ("Smolderwing Whelp", 441, 0.4, 19054, "Sneezes sparks. Keep it away from the maps."),
      ("Firegut Ogre Brew", 2686, 7033, "a Firegut ogre")),
    Z(8, "Swamp of Sorrows", "Sorrowmoor Wanderer",
      ("Tabard of the Harborage", 81085), ("Misty Reed Drape", 12110),
      ("Bogbean Tea", 10841, "Mire Resilience", "resist_nature"),
      ("Pool of Tears Lotus", 61199, "SwampOfSorrows", "the Swamp of Sorrows"),
      ("Sawtooth Snapper", 1084, 0.3, 18964, "All teeth, no manners."),
      ("Lost One Fishing Bait", 8151, 757, "a Lost One")),
    Z(4, "Blasted Lands", "Portal Watcher",
      ("Tabard of Nethergarde", 81083), ("Tainted Scar Mantle", 6832),
      ("Nethergarde Bitters", 4595, "Felward", "resist_shadow"),
      ("Nethergarde Keep Sigil", 7291, "BlastedLands", "the Blasted Lands"),
      ("Snickerfang Pup", 5985, 0.35, 10394, "Laughs at its own jokes. Only its own."),
      ("Fel-Tainted Elixir", 8529, 6010, "a felhound")),
    Z(41, "Deadwind Pass", "Karazhan Trespasser",
      ("Tabard of the Violet Eye", 81203), ("Deadwind Phantom Cape", 13122),
      ("Moroes' Midnight Tea", 10841, "Ley-Touched", "resist_arcane"),
      ("Karazhan Gate Key Fragment", 2629, "DeadwindPass", "Deadwind Pass"),
      ("Mist Fox Kit", 80258, 0.4, 36500, "Fades into the fog whenever you need it."),
      ("Restless Shade Essence", 61224, 7370, "a restless shade")),
    Z(5179, "Gilneas", "Gilnean Loyalist",
      ("Greymane Wall Tabard", 61368), ("Ravenshire Darcy Shirt", 41270),
      ("Shademore Tavern Ale", 2686, "Gilnean Grit", "damage_taken"),
      ("Stillward Church Bell", 1630, "stillward", "Stillward Church"),
      ("Duskpelt Pup", 61229, 0.35, 69000, "A proper Gilnean hound, apart from the curse."),
      ("Nighthowl Curse Vial", 8529, 61236, "a Nighthowl worgen")),
    Z(408, "Gillijim's Isle", "Islander of Gillijim",
      ("Tabard of the Silver Coast", 81088), ("Southsea Corsair's Shirt", 6796),
      ("Distillery Island Rum", 20709, "Island Breeze", "speed"),
      ("Silver Coast Seashell", 92020, "silvercoast", "the Silver Coast"),
      ("Junglepaw Cub", 91960, 0.35, 36505, "Purrs like a ship's engine."),
      ("Razzari Ritual Paint", 51245, 92150, "a Razzari troll")),
    Z(409, "Lapidis Isle", "Castaway of Lapidis",
      ("Tabard of Caelan's Rest", 81084), ("Lapidis Arcanist's Cape", 8286),
      ("Caelan's Coconut Milk", 1179, "Tidewalker", "swim"),
      ("Caelan's Rest Driftwood", 3408, "caelansrest", "Caelan's Rest"),
      ("Bengal Tiger Cub", 91825, 0.35, 23712, "Escaped the Tower of Lapidis. Chose you instead."),
      ("Gor'dosh Ogre Grog", 2686, 91848, "a Gor'dosh ogre")),
    Z(5225, "Thalassian Highlands", "Ranger of the Highlands",
      ("Farstrider Tabard", 80317), ("Farstrider's Autumn Cloak", 80506),
      ("Thalassian Sunwine", 2723, "Sunstrider's Grace", "stats"),
      ("Silver Covenant Runestone", 3408, "thalassianhighlands", "the Thalassian Highlands"),
      ("Crimson Lynx Kitten", 61690, 0.4, 80001, "Chases autumn leaves. Catches some."),
      ("Mana Wyrm Essence", 61199, 61774, "a mana wyrm")),
    Z(2040, "Alah'Thalas", "Citizen of Alah'Thalas",
      ("Tabard of Alah'Thalas", 80310), ("Magister's Silk Shirt", 10054),
      ("Alah'Thalas Arcane Tea", 10841, "Arcane Insight", "regen"),
      ("Alah'Thalas Gate Crystal", 61199, "alahthalasentrance", "the gates of Alah'Thalas"),
      ("Tiny Arcane Guardian", 80506, 0.3, 80006, "Guards you. Mostly from dust."),
      ("Magister's Glamour", 8529, 80234, "an Alah'Thalas magister")),
    Z(4012, "Scarlet Enclave", "Scourge of New Avalon",
      ("Defaced Scarlet Tabard", 7725), ("Tyr's Hand Inquisitor Cloak", 10194),
      ("Havenshire Cider", 4595, "Zealot's Fervor", "damage"),
      ("New Avalon Town Key", 2629, "scarletenclave", "the cliffs above New Avalon"),
      ("Scarlet Warhorse Foal", 40023, 0.3, 50007, "Defected from the Crusade. Still salutes."),
      ("Scarlet Paladin's Tabard Kit", 51245, 1834, "a Scarlet paladin")),
    # --- Kalimdor -----------------------------------------------------------------------------
    Z(14, "Durotar", "Hero of Razor Hill",
      ("Tabard of Razor Hill", 80307), ("Sen'jin Brawler's Harness", 6125),
      ("Cactus Apple Surprise", 5474, "Desert Toughness", "health"),
      ("Echo Isles Voodoo Charm", 19813, "Durotar", "the heart of Durotar"),
      ("Durotar Scorpling", 3124, 0.4, 10393, "Its sting tickles. Usually."),
      ("Burning Blade Cultist Robes", 8529, 3199, "a Burning Blade cultist")),
    Z(215, "Mulgore", "Plainsrunner of Mulgore",
      ("Tabard of Bloodhoof Village", 80308), ("Bloodhoof Hunter's Cape", 3561),
      ("Bloodhoof Kodo Stew", 12215, "Earthmother's Blessing", "healing"),
      ("Red Rocks Totem", 50374, "Mulgore", "Stonebull Lake"),
      ("Prairie Wolf Pup", 2958, 0.35, 10394, "Howls along whenever anyone plays a drum."),
      ("Bristleback Snout", 777, 2952, "a quilboar")),
    Z(17, "The Barrens", "Mankrik's Confidant",
      ("Tabard of the Golden Savannah", 81087), ("Plainsrunner's Dust Cloak", 6789),
      ("Crossroads Kodo Jerky", 5474, "Kodo Endurance", "speed"),
      ("Ratchet Dock Token", 51603, "Ratchet", "Ratchet"),
      ("Plainstrider Chick", 2955, 0.35, 81243, "Has already outrun a raptor. Probably by accident."),
      ("Kolkar Hide Costume", 6657, 3272, "a Kolkar centaur")),
    Z(141, "Teldrassil", "Child of Teldrassil",
      ("Tabard of Dolanaar", 80305), ("Shadowglen Leafweave Cloak", 9770),
      ("Dolanaar Moonberry Tonic", 1645, "Moonlit Grace", "dodge"),
      ("Aldrassil Seedpod", 61199, "Teldrassil", "the boughs of Teldrassil"),
      ("Timberling Sapling", 2022, 0.3, 51007, "Needs sunlight, water and constant praise."),
      ("Gnarlpine Totem Mask", 51245, 7235, "a Gnarlpine furbolg")),
    Z(148, "Darkshore", "Warden of Darkshore",
      ("Tabard of Auberdine", 80301), ("Darkshore Tidewatcher Cape", 4114),
      ("Auberdine Sea Bass", 13934, "Sea Mist", "armor"),
      ("Darkshore Moonstone", 61199, "Darkshore", "the Darkshore coast"),
      ("Moonkin Hatchling", 10159, 0.35, 8500, "Bobs its head to music only it can hear."),
      ("Greymist Murloc Scale", 777, 46, "a murloc")),
    Z(331, "Ashenvale", "Sentinel of Ashenvale",
      ("Silverwing Sentinel Tabard", 19506), ("Astranaar Moonfeather Cloak", 41041),
      ("Forest Song Elderberry Wine", 2723, "Wisdom of the Ancients", "regen"),
      ("Moonwell Dewdrop", 8766, "Ashenvale", "Nightsong Woods"),
      ("Ashenvale Wisp", 3681, 0.5, 69006, "Glows softer when you are sad."),
      ("Ancient's Acorn", 61199, 5806, "a treant")),
    Z(406, "Stonetalon Mountains", "Guardian of Stonetalon",
      ("Tabard of Sun Rock", 81082), ("Windshear Crag Cloak", 5610),
      ("Sun Rock Sweet Tea", 10841, "Mountain Wind", "speed"),
      ("Stonetalon Peak Feather", 11417, "StonetalonPeak", "Stonetalon Peak"),
      ("Thunderhawk Hatchling", 3247, 0.4, 80878, "Crackles when it is happy. Do not pet it in the rain."),
      ("Venture Co. Hard Hat", 2629, 3989, "a Venture Co. goblin")),
    Z(405, "Desolace", "Wanderer of Desolace",
      ("Tabard of the Gelkis Accord", 81202), ("Ghost Walker's Shroud", 11873),
      ("Shadowprey Smoked Fish", 13934, "Desolate Endurance", "damage_taken"),
      ("Kodo Graveyard Bone", 80166, "Desolace", "the Desolace wastes"),
      ("Thunder Lizard Hatchling", 3130, 0.3, 18963, "Its tail sparks. Its heart is gold."),
      ("Magram Centaur Hide", 6657, 4639, "a Magram centaur")),
    Z(400, "Thousand Needles", "Mirage Racer",
      ("Mirage Raceway Racing Tabard", 81086), ("Pit Crew Shirt", 11840),
      ("Fizzle's Nitro Soda", 1645, "Speed Demon", "speed"),
      ("Mirage Raceway Checkered Flag", 17849, "MirageRaceway", "the Mirage Raceway"),
      ("Salt Flats Vulture Chick", 4158, 0.3, 81243, "Watches the races. Bets on the gnomes."),
      ("Grimtotem Warpaint", 51245, 7725, "a Grimtotem tauren")),
    Z(15, "Dustwallow Marsh", "Marsh Warden",
      ("Tabard of Theramore", 50088), ("Mudsprocket Rain Poncho", 3561),
      ("Mudsprocket Swamp Brew", 61224, "Marsh Endurance", "resist_nature"),
      ("Mudsprocket Bolt", 2629, "mudsprocket", "Mudsprocket"),
      ("Swamp Jaguar Cub", 767, 0.35, 36505, "Prefers the mud. Prefers your lap more."),
      ("Theramore Guard Uniform", 51245, 4979, "a Theramore guard")),
    Z(357, "Feralas", "Twin Colossals Explorer",
      ("Tabard of Feathermoon", 80318), ("Grimtotem Feathered Cloak", 5971),
      ("Camp Mojache Spring Water", 8766, "Wild Vigor", "attack_power"),
      ("Twin Colossals Arrowhead", 3408, "Travelerbasecamp", "the Twin Colossals"),
      ("Frayfeather Hippogryph Chick", 5300, 0.3, 80878, "Has not yet worked out which half is in charge."),
      ("Gordunni Ogre Brew", 2686, 5229, "a Gordunni ogre")),
    Z(440, "Tanaris", "Steamwheedle Associate",
      ("Steamwheedle Cartel Tabard", 80316), ("Gadgetzan Merchant's Shirt", 92019),
      ("Gadgetzan Water Ration", 8766, "Desert Hydration", "health"),
      ("Gadgetzan Teleport Coin", 51603, "Gadgetzan", "Gadgetzan"),
      ("Lil' Shellback", 6369, 0.3, 18964, "Slow and steady. Mostly slow."),
      ("Wastewander Bandana", 51245, 5615, "a Wastewander bandit")),
    Z(16, "Azshara", "Highborne Scholar",
      ("Tabard of Talrendis", 80300), ("Eldarath Highborne Shawl", 14450),
      ("Bay of Storms Kelp Tea", 10841, "Highborne Insight", "crit"),
      ("Tower of Eldara Fragment", 60464, "Azshara", "the shores of Azshara"),
      ("Lil' Aberration", 11480, 0.3, 80006, "Hums with stolen arcane power. It means well."),
      ("Highborne Lichling Dust", 80166, 6117, "a Highborne lichling")),
    Z(361, "Felwood", "Purifier of Felwood",
      ("Tabard of the Emerald Sanctuary", 80301), ("Timbermaw Totemic Cloak", 4113),
      ("Felwood Cleansed Water", 8766, "Cleansing Light", "resist_shadow"),
      ("Emerald Sanctuary Leaf", 61199, "EmeraldSanctuary", "the Emerald Sanctuary"),
      ("Felpaw Pup", 8959, 0.35, 50085, "Cleansed of fel. Still chews boots."),
      ("Jadefire Satyr Horn", 777, 7105, "a Jadefire satyr")),
    Z(493, "Moonglade", "Moonglade Pilgrim",
      ("Tabard of Nighthaven", 80301), ("Lake Elune'ara Moonshroud", 18734),
      ("Nighthaven Moonwell Water", 8766, "Elune's Grace", "healing"),
      ("Moonglade Wisp Lantern", 2714, "Nighthaven", "Nighthaven"),
      ("Nighthaven Owlet", 1995, 0.4, 8500, "Hoots softly at the moon every night."),
      ("Moonkin Feather Costume", 11417, 10158, "a moonkin")),
    Z(618, "Winterspring", "Winterspring Pathfinder",
      ("Tabard of Everlook", 23709), ("Frostsaber Fur Cloak", 7377),
      ("Winterspring Mulled Wine", 2723, "Frostwarden", "resist_frost"),
      ("Everlook Snowglobe", 60464, "Everlook", "Everlook"),
      ("Frostsaber Kitten", 7430, 0.4, 36505, "Pounces on snowflakes. Misses."),
      ("Winterfall Totem", 51245, 7439, "a Winterfall furbolg")),
    Z(490, "Un'Goro Crater", "Crater Explorer",
      ("Tabard of Marshal's Refuge", 81085), ("Ravasaur Hide Cloak", 15309),
      ("Power Crystal Tonic", 61224, "Crystal Charge", "damage"),
      ("Un'Goro Power Crystal", 61199, "Marshal'sRefuge", "Marshal's Refuge"),
      ("Ravasaur Hatchling", 6505, 0.3, 81183, "Hunts your bootlaces with deadly focus."),
      ("Pterrordax Feather", 11417, 9165, "a pterrordax")),
    Z(1377, "Silithus", "Scourge of the Hive",
      ("Tabard of Cenarion Hold", 81205), ("Qiraji Scarab Shirt", 81142),
      ("Cenarion Hold Desert Tea", 10841, "Sandward", "resist_nature"),
      ("Cenarion Hold Scarab", 60267, "CenarionHold", "Cenarion Hold"),
      ("Silithid Grubling", 3251, 0.4, 92020, "Hatched far from the hive. Loves you instead."),
      ("Dust Stormer Essence", 61224, 11744, "a dust stormer")),
    Z(616, "Hyjal", "Defender of Nordrassil",
      ("Tabard of Nordanaar", 81085), ("Barkskin Grovewalker Cloak", 17739),
      ("Nordrassil Dewdrop", 8766, "Nordrassil's Blessing", "stats"),
      ("Nordrassil Acorn", 61199, "nordanaar", "Nordanaar"),
      ("Misthoof Fawn", 61332, 0.3, 51433, "Born under the World Tree. Acts like it."),
      ("Barkskin Furbolg Totem", 51245, 61343, "a Barkskin furbolg")),
    Z(5121, "Tel'Abim", "Banana Baron",
      ("Tel Co. Tabard", 81087), ("Tel'Abim Tropical Shirt", 17723),
      ("Tel'Abim Banana Split", 4537, "Potassium Rush", "attack_power"),
      ("Tel Co. Basecamp Voucher", 51603, "telabim", "the Tel Co. Basecamp"),
      ("Highvale Monkey", 61078, 0.35, 61520, "Will steal your bananas. All of them."),
      ("Gorilla Suit", 6657, 61074, "a Highvale gorilla")),
    Z(5536, "Blackstone Island", "Blackstone Islander",
      ("Tabard of Rustgate", 81089), ("Black Ash Miner's Shirt", 2105),
      ("Venture Co. Coffee", 10841, "Overtime Shift", "hit"),
      ("Rustgate Ridge Cog", 2629, "blackstone", "Rustgate Ridge"),
      ("Mine-Bot Jr.", 61687, 0.4, 50005, "Malfunctions adorably."),
      ("Mudpaw Gnoll Mask", 777, 61663, "a Mudpaw gnoll")),
    Z(5024, "Icepoint Rock", "Friend of Kaneq'nuun",
      ("Tabard of Kaneq'nuun", 23709), ("Whiteclaw Fur Cloak", 4327),
      ("Kaneq'nuun Fish Stew", 12215, "Arctic Hardiness", "resist_frost"),
      ("Kaneq'nuun Bone Charm", 80166, "icepointrock", "Kaneq'nuun"),
      ("Glacier Penguin Chick", 70040, 0.4, 21309, "Waddles with great dignity."),
      ("Tuskarr Disguise", 6657, 60543, "a tuskarr")),
]
